# Website 1: Tích hợp API Node-RED
server {
    listen 80;
    server_name web1.thanhdayne.id.vn;

    location / {
        root /usr/share/nginx/html/site1;
        index index.html;
    }

    # Proxy kết nối /api/ sang Node-RED
    location /api/ {
        proxy_pass http://nodered:1880/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}

# Website 2: Website thứ hai chạy song song
server {
    listen 80;
    server_name web2.thanhdayne.id.vn;

    location / {
        root /usr/share/nginx/html/site2;
        index index.html;
    }
}
